<?php

namespace UserBundle\Repository;

/**
 * CyPermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CyPermissionRepository extends \Doctrine\ORM\EntityRepository
{
}
