<?php

namespace UserBundle\Repository;

/**
 * CyRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CyRoleRepository extends \Doctrine\ORM\EntityRepository
{    
}
