services:
    User.AccesGrant:
        class: UserBundle\EventListener\AccesGrant
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: grant }